apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: default
  labels:
    app: devops
spec:
  type: NodePort
  selector:
    app: devops
  ports:
  - name: http
    port: 80           # Service port (Ingress connects here)
    targetPort: 3000   # Container port
    nodePort: 30009    # External port for direct access
    protocol: TCP